---
name: test
on:
  push:
    branches:
      - main
      - v2
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Install go-ctrf-json-reporter
        run: go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
      - name: Run tests
        run: go test -json ./... | go-ctrf-json-reporter -o test-results.json
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@e500b992f936420eb633c91644cf10d4d71df700 # v1.1.0
        with:
          report-path: test-results.json
          github-report: true
        if: always()
